### ISSUE TITLE
Feature Request: Builder-style condition statements

### ISSUE THREAD

**Issue by erawhctim** [s4kibs4mi/PultusORM#1]
It'd be great if the conditional methods in `PultusORMCondition` were treated like methods on a traditional Builder class.  

So the following example: 
```
val condition: PultusORMCondition = PultusORMCondition()
condition.sort("studentId", PultusORMQuery.Sort.DESCENDING)  // Want to get value descending sorted by studentId
condition.eq("studentId", 2)
condition.or()
condition.eq("studentId", 4)
```

could be come this:
```
val condition: PultusORMCondition = PultusORMCondition.Builder()
    .sort("studentId", PultusORMQuery.Sort.DESCENDING)
    .eq("studentId", 2)
    .or()
    .eq("studentId", 4)
    .build()
```

There might be some more work handling edge cases around the `and()`s and `or()`s that I didn't outline here, but this would be a nice to have feature. I'll leave this open for discussion or any suggestions around this implementation 👍

**Comment by s4kibs4mi** [comment]
@erawhctim thanks for your suggestion. I really appreciate it and your suggestion seems good. If you could add this feature that will be great or i will try to implement it on next release. :)

**Comment by s4kibs4mi** [comment]
hello @erawhctim I have updated condition as builder style and will change updater on next release. :)
