### ISSUE TITLE
Builder in UpdateQuery not able to set more than one value

### ISSUE THREAD

**Issue by dengelma** [s4kibs4mi/PultusORM#13]
The Builder factory in PultusORMUpdater is not able to set more than one value for the updated item in one step.

There comes this Exception: `Malformed update query` when doing something like 
```kotlin
val updater: PultusORMUpdater = PultusORMUpdater.Builder()
  .set("team", team)
  .set("placement", placement)
  .set("points", points)
  .set("difference", difference)
  .set("favourite", favourite)
  .build()
db.update(TabelleORM(), updater)
```

In your Wiki on the update page there isn`t an example for updating more than one value.

**Comment by s4kibs4mi** [comment]
@dengelma , it should update multiple fields. Can you please use update method with callback parameter ? it will give you full trace log.
Something like this. Note that update with callback is an async process.

```kotlin
class ResponseCallback : Callback {
    override fun onSuccess(type: PultusORMQuery.Type) {
        log("${type.name}", "Success")
    }

    override fun onFailure(type: PultusORMQuery.Type, exception: PultusORMException) {
        log("${type.name}", "Failure")
        exception.printStackTrace()
    }
}

val updater: PultusORMUpdater = PultusORMUpdater.Builder()
  .set("team", team)
  .set("placement", placement)
  .set("points", points)
  .set("difference", difference)
  .set("favourite", favourite)
  .build()

db.update(TabelleORM(), updater, ResponseCallback())
```

**Comment by dengelma** [comment]
Thanks for the really fast response.
I will try it later because in my case I figured out that I do not really need the update method. But thanks anyway
