### ISSUE TITLE
Could Not Open Database

### ISSUE THREAD

**Issue by TedHoryczun** [s4kibs4mi/PultusORM#15]
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database

When running: 
        val pultusORM: PultusORM = PultusORM("workout.db")

**Comment by s4kibs4mi** [comment]
@TedHoryczun , Please provide system information. Also check if you have file create permission on root directory.

**Comment by TedHoryczun** [comment]
Android OS Version: 4.4
I also have create permissions. 
A regular SQLiteOpenHelper can write and read from DB.

**Comment by s4kibs4mi** [comment]
@TedHoryczun , In android you have to specify database path. Like,
`val pultusORM: PultusORM = PultusORM("workout.db", "path_to_database")`

If you want to put db in files directory of application this is the code snippet,
```
val appPath = getApplicationContext().getFilesDir().getAbsolutePath()
val pultusORM = PultusORM("workout.db", appPath)
```

**Comment by TedHoryczun** [comment]
I'll try that out and, update on the progress.

**Comment by juanchosaravia** [comment]
It works as @s4kibs4mi said but this for sure should be in the readme to avoid frustration.

**Comment by s4kibs4mi** [comment]
@juanchosaravia , thanks for your feedback. I will add this in readme.
