### ISSUE TITLE
What if I just wanted to count?

### ISSUE THREAD

**Issue by Bernix01** [s4kibs4mi/PultusORM#16]
It'd be great to have just the count of query result without loading it all to memory 🔢

**Comment by s4kibs4mi** [comment]
@Bernix01 Thanks for your feedback. Will improve it in next version :) and if you wish feel free to contribute :)

**Comment by s4kibs4mi** [comment]
@Bernix01 count without loading data in memory added. [commit-9104c66c7ac5bbcab40116468531770522326608](https://github.com/s4kibs4mi/PultusORM/commit/9104c66c7ac5bbcab40116468531770522326608)
