### ISSUE TITLE
Error when string contains apostrophe (')

### ISSUE THREAD

**Issue by eleddie** [s4kibs4mi/PultusORM#17]
I'm getting this error `E/SQLiteLog: (1) near "s": syntax error` when trying to save a string which contains an apostrophe in it.

**Comment by mustafaozhan** [comment]
Please check these code, how handling ' character in SQLite. The issue about SQLite not with PultusORM.
`if (item.contains("'")) {
            item = item.replaceAll("'", "''");
        }`
