### ISSUE TITLE
External Database

### ISSUE THREAD

**Issue by mustafaozhan** [s4kibs4mi/PultusORM#18]
Is there any way to use it with external database located in assets/databases ?

**Comment by s4kibs4mi** [comment]
@mustafaozhan 100%. Just use absolute path of the folder. Be sure that you have read write permission to the folder.

**Comment by s4kibs4mi** [comment]
And make sure your class name, instance name equivalent to table name and field name.

**Comment by mustafaozhan** [comment]
It is working. But i couldn't get my database from asset/databases instead of it i copied database to /data/data/packagename/files

**Comment by s4kibs4mi** [comment]
@mustafaozhan could be you don't have write permission to asset folder.
