### ISSUE TITLE
all fields have to be filled to save object?

### ISSUE THREAD

**Issue by mikepschneider** [s4kibs4mi/PultusORM#20]
It seems that every field in an object has to have a value in order for it to be saved to the DB.  Is that accurate?  When I run the following code it outputs `objects = 1.` If I set `s2.department = "X";` then it outputs `objects = 2`.

Is there any way around this?  Thanks for the response.
```
  public void onCreate() {
    super.onCreate();
    String appPath = getApplicationContext().getFilesDir().getAbsolutePath();
    pultusORM = new PultusORM("app.db", appPath);
    pultusORM.drop(new Student());

    Student s = new Student();
    s.name = "ALEX";
    s.department = "X";
    pultusORM.save(s);

    Student s2 = new Student();
    s2.name = "ABC";
    pultusORM.save(s2);

    List<Object> objects = PilotApp.getDB().find(new Student());
    Timber.e("objects =  " + objects.size());
  }


  public static class Student {
    @PrimaryKey
    @AutoIncrement
    public int studentId;
    public String name;
    String department;
  }
```

**Comment by s4kibs4mi** [comment]
@mikepschneider , if you want to keep a field empty or unassigned annotate that value with NotNull annotation. Hope it will solve your problem.

**Comment by s4kibs4mi** [comment]
@mikepschneider , if you don't annotated the the field with NotNull annotation it should save null value.

**Comment by mikepschneider** [comment]
The issue is it is not saving **the entire object** if there is one null field on the object.  Is that the expected behavior??  Because that is very unexpected and undesirable behavior from my perspective to silently ignore an entire object when one field is null.  Please clarify if that is expected or not expected.

**Comment by s4kibs4mi** [comment]
@mikepschneider , Me also don't expect the behavior to be this and it's unexpected. Let me check your example and if anything unexpected happen surely I will give a solution.

**Comment by s4kibs4mi** [comment]
@mikepschneider , it was a bug. Many thanks for pointing out it. I have provided a fix for this. Please update the library to v1.5 to get latest release or check readme.
