### ISSUE TITLE
Ignore Bug debugged

### ISSUE THREAD

**Issue by mynote** [s4kibs4mi/PultusORM#25]
After spending hours to find the "stackoverflowerror", ive decided to download your source.

Splitting your source exposed that that you parse the ignore successfull, but com.eclipsesource.minimal-json does not.

Since it uses gson to parse, it requires to use @Expose or @Transient over @Ignore.

This could be a pain debugging because in my case i had a PropertyChangeSupport which was not debuggable.

Fix: create your own json parser or use gson's annotations.

**Comment by s4kibs4mi** [comment]
@mynote , Can you please post the debuglog ? or details about the scenario ?

**Comment by mynote** [comment]
Debugging was not possible since it always leads to an stackoverflowerror.  After slicing my whole javafx code, i figured out that the reason was the PropertyChangeSupport which is usually used to bind beans and listen for changes.

Even after using your libs @Ignore didnt help. Then i tried to comment out everything in your lib which may causes that issue. 

Them i figured out that it was 

fun objectAsJson(value: Any): JsonObject {
    return Json.parse(objectToJsonConverter.toJson(value)).asObject()
}

After validating the instance which is used by this library i figured out that it uses GSON and GSON's Ignore (not yours) to ignore fields for serializing.

Then ive added gson to my libs and used gsons @Ignore to my PropertyChangeSupport and the issue was solved.

**Comment by s4kibs4mi** [comment]
Hello @mynote , I have tested the ignore annotation and its working fine. There could be something else which is make issue in your code. I am closing the issue.
