### ISSUE TITLE
Missing replace

### ISSUE THREAD

**Issue by mynote** [s4kibs4mi/PultusORM#26]
There's an important feature missing. Its called replace. 

e.g.

insert or replace into Book (ID, Name, TypeID, Level, Seen) values
((select ID from Book where Name = "SearchName"), "SearchName", ...);

Not sure if raw queries are possible, but this would help to do that.

**Comment by s4kibs4mi** [comment]
Hello @mynote thanks for your feedback. I have plan to implement a function like `insertOrUpdate`, I think its similar to `insertOrReplace`. Check [this issue](https://github.com/s4kibs4mi/PultusORM/issues/4). I really appreciate if you can contribute.

**Comment by mynote** [comment]
First extension, cleaned up a little bit. Just contact me if you want to contribute a new library which is completly reworked since the code base is good, but requires lot of changes.


`    
    enum class Type {
        SAVE,
        UPDATE,
        DELETE,
        DROP,
        REPLACE,
        IGNORE
    }


    /**
     * Method to save value
     * @param clazz
     */
    fun save(clazz: Any, insertType: Type = Type.SAVE): Boolean {
        try {
            createTable(clazz)

            statement.execute(Builder().insert(clazz))
            log(this.javaClass.simpleName, "Inserted into ${clazz.javaClass.simpleName} - Succeed")
            return true
        } catch (exception: Exception) {
            log(this.javaClass.simpleName, "Inserted into ${clazz.javaClass.simpleName} - Failed <${exception.message}>")
        }
        return false
    }

    /**
     * Method to save value with callback
     * @param clazz
     * @param callback
     */
    fun save(clazz: Any, callback: Callback, insertType: Type = Type.SAVE) {
        thread(start = true) {
            try {
                createTable(clazz)
                statement.execute(Builder().insert(clazz, insertType))
                callback.onSuccess(Type.SAVE)
            } catch (exception: Exception) {
                exception.printStackTrace()
                exception.message?.let { callback.onFailure(Type.SAVE, PultusORMException(it)) }
            }
        }
    }


fun insert(clazz: Any, insertType: Type = Type.SAVE): String {
            val objectAsJson = objectAsJson(clazz)
            val queryBuilder = StringBuilder()

            when (insertType) {
                Type.REPLACE -> queryBuilder.append("INSERT OR REPLACE")
                Type.IGNORE -> queryBuilder.append("INSERT OR IGNORE")
                else -> queryBuilder.append("INSERT")
            }

            queryBuilder.append(" INTO ${clazz.javaClass.simpleName}")

            val keyBuilder = StringBuilder("(")
            val valueBuilder = StringBuilder(" VALUES(")

            val fields = clazz.javaClass.declaredFields + clazz.javaClass.superclass.declaredFields

            var isFirst = true
            for (field in fields) {
                if (objectAsJson.get(field.name) != null && isIgnoreField(field).not() && isAutoGeneratedClassMetaDataField(field).not()) {
                    if (isAutoIncrement(field))
                        continue

                    if (isFirst.not()) {
                        keyBuilder.append(",")
                        valueBuilder.append(",")
                    }
                    log("fieldname", field.name)

                    keyBuilder.append(field.name)
                    if (objectAsJson.get(field.name).isString) {
                        valueBuilder.append("'${objectAsJson.getString(field.name, "")}'")
                    } else if (objectAsJson.get(field.name).isBoolean) {
                        if (objectAsJson.getBoolean(field.name, false))
                            valueBuilder.append("1")
                        else valueBuilder.append("0")
                    } else valueBuilder.append(objectAsJson.get(field.name))

                    isFirst = false
                }
            }

            keyBuilder.append(")")
            valueBuilder.append(")")

            queryBuilder.append(keyBuilder)
            queryBuilder.append(valueBuilder)
            queryBuilder.append(";")

            log(this.javaClass.simpleName, queryBuilder.toString())
            return queryBuilder.toString()
        }
`
