### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by mynote** [s4kibs4mi/PultusORM#27]
Cleaning the code and make it more "kotlin-like" would be great. Using closable stuff is better. Example:

    fun select(clazz: Any, condition: PultusORMCondition) = if (condition.rawQuery().trim().isNotEmpty())
            "SELECT * FROM ${clazz.javaClass.simpleName} ${condition.rawQuery()};" else select(clazz)

        fun select(clazz: Any) = "SELECT * FROM ${clazz.javaClass.simpleName};"
        fun delete(clazz: Any) = "DELETE FROM ${clazz.javaClass.simpleName};"
        fun delete(clazz: Any, condition: PultusORMCondition) = "DELETE FROM ${clazz.javaClass.simpleName} ${condition.rawQuery()};"
        fun drop(clazz: Any) = "DROP TABLE ${clazz.javaClass.simpleName};"

     private fun isTableExists(tableName: String) =
            statement.executeQuery("SELECT * FROM ${SqliteSystem.getTableName()}" +
                    " WHERE type='${SqliteSystem.Type.TABLE.name.toLowerCase()}' AND name='$tableName';")
                    .use {
                        val isExist = it.next()
                        if (isExist)
                            log(this.javaClass.simpleName, "table $tableName already exists.")
                        else log(this.javaClass.simpleName, "table $tableName not exists")
                        return@use isExist
                    }

**Comment by s4kibs4mi** [comment]
@mynote thanks for the feedback.
