### ISSUE TITLE
SQLDroidResultSet implementation

### ISSUE THREAD

**Issue by mick340** [s4kibs4mi/PultusORM#30]
When i do a find() with my class wich contaings a createdAt, updatedAt and deletedAt i get the warning 

`W/System.err:  ********************* not implemented @ org.sqldroid.SQLDroidResultSet (getDate) line 290` 

This error comes from SQLDroidResultSet.java line 290 from the method 

`  @Override
  public Date getDate(String columnName) throws SQLException {
    System.err.println(" ********************* not implemented @ " + DebugPrinter.getFileName() + " line " + DebugPrinter.getLineNumber());
    return null;
  }`

Is there anyway to avoid this warning? Do we need to implement something to avoid this?

**Comment by s4kibs4mi** [comment]
@mick340 I am closing the issue. Please reopen it if you still face the problem.

**Comment by mick340** [comment]
Hi im going to test this tomorrow

Op do 31 mei 2018 22:03 schreef Sakib Sami <notifications@github.com>:

**Comment by mick340** [comment]
I still have the issue

**Comment by s4kibs4mi** [comment]
Hello @mick340 sorry to hear that. Please give me details info or trace log otherwise it's tough to solve the issue or find out what's going wrong.
